package net.imagej.fijiyama.registration;

public enum OptimizerType {
	ITK_GRADIENT,
	ITK_GRADIENT_REGULAR_STEP,
	ITK_GRADIENT_LINE_SEARCH,
	ITK_GRADIENT_CONJUGATE,
	ITK_LBFGSB,
	ITK_LBFGS2,
	ITK_POWELL,
	ITK_EVOLUTIONARY,
	ITK_EXHAUSTIVE,
	ITK_AMOEBA,
	BLOCKMATCHING,
	MASSCENTER,
	INERTIA_AXIS
}
